#
# WP YAML Fixtures build process for Travis CI
#


#
# !!! IMPORTANT !!!
#
# "without the top-level `env`, no job will be allowed to fail."
# https://docs.travis-ci.com/user/customizing-the-build/
#
# uncomment this line to allow some jobs to fail:
#env:


language: php

install: composer install --prefer-dist

php:
- '7.0'
- '7.1.25'
- '7.2'
- '7.3'

script:
  - composer test


# Test WP YAML Fixtures against PHP 7.x and run end-to-end tests
matrix:
  include:
    - name: 'Coding standards'
      script: composer sniff

  allow_failures:
    - name: 'Coding standards'
    - php: '7.3'
